# Generated by Django 5.2.3 on 2025-09-28 22:41

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('voting', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='full_name',
            field=models.CharField(blank=True, help_text='Full name of the user', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Team/Candidate name', max_length=200)),
                ('description', models.TextField(blank=True, help_text='Brief description', null=True)),
                ('image', models.ImageField(blank=True, help_text='Team logo or promotional image', null=True, upload_to='team_images/')),
                ('program_document', models.FileField(blank=True, help_text='PDF document with election program', null=True, upload_to='team_programs/')),
                ('contact_info', models.TextField(blank=True, help_text='Contact information for the team', null=True)),
                ('is_active', models.BooleanField(default=True, help_text='Is this team currently active?')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='created_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Team',
                'verbose_name_plural': 'Teams',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='option',
            name='team',
            field=models.ForeignKey(blank=True, help_text='Team associated with this option', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='options', to='voting.team'),
        ),
    ]
